### ISSUE TITLE
Is there a way to get an RA-01 without a DIO2 pin work?

### ISSUE THREAD

**Issue by DanielKinsman** [cpainchaud/RFLink#122]
I stupidly bought this module which does not expose the DIO2 pin of the SX1278: https://www.aliexpress.com/item/1005006864170059.html?spm=a2g0o.order_list.order_list_main.15.2f1e1802phqlwc

![image](https://github.com/user-attachments/assets/1501c169-57ed-4bae-a83f-f69fd7c9d112)

Apart from attempting to disassemble and re-solder the chip, is there anything I can do in software to get it to work with the DIO0 pin?

Thanks for making this great software.

**Comment by cpainchaud** [comment]
may be directly on the module?

![image](https://github.com/user-attachments/assets/91533286-a240-4939-8a1d-c51334619dba)

![image](https://github.com/user-attachments/assets/587f5be7-3531-43ea-9618-44c38da161c2)

**Comment by DanielKinsman** [comment]
I tried but sadly it did not work, probably due to my poor soldering skills.

![20241217_083602](https://github.com/user-attachments/assets/a77a2b85-e113-4f0d-bc2b-d6a5249f3501)

Netcat just gives:
`Now trying to initialize hardware 'SX1278'
Hardware failed to initialize, we will retry later!`

Thanks for your help though.
