### ISSUE TITLE
Newkakku is not decrypted with default settings

### ISSUE THREAD

**Issue by schmurtzm** [cpainchaud/RFLink#13]
sample rate is set to 1 by default -> newkaku is not decrypted.
It is OK with sample rate = 6 and more.

Below 3 debug trace of the new kaku (sample rate 1 , and 32)

[newkaku - sample rate tests.txt](https://github.com/cpainchaud/RFLink/files/6151226/newkaku.-.sample.rate.tests.txt)

**Comment by cpainchaud** [comment]
fixed! :)
